Repository caicloud/ciao, pull requests merged in 2018-09, with the labels that each got.

#1 *: Add first version of the code
  .gitignore
  Gopkg.lock
  Gopkg.toml
  OWNERS
  README.md
  artifacts/kernel.json
  cmd/kubeflow-kernel/main.go
  docs/demo.md
  docs/examples/example.ipynb
  docs/installation.md
  hack/install.sh
  pkg/backend/kubeflow/kubeflow.go
  pkg/backend/kubeflow/labels.go
  pkg/backend/types.go
  pkg/interpreter/simple/simple.go
  pkg/interpreter/simple/simple_test.go
  pkg/interpreter/types.go
  pkg/kernel/kernel.go
  pkg/kernel/messages.go
  pkg/kernel/socket.go
  pkg/kernel/types.go
  pkg/kernel/utils.go
  pkg/manager/manager.go
  pkg/manager/utils.go
  pkg/s2i/mock/mock.go
  pkg/s2i/simple/simple.go
  pkg/s2i/types.go
  pkg/types/types.go
  s2i/tensorflow-s2i/Dockerfile
  s2i/tensorflow-s2i/s2i/bin/assemble
  s2i/tensorflow-s2i/s2i/bin/run
  s2i/tensorflow-s2i/s2i/bin/usage
  s2i/tensorflow-s2i/test/test-app/code.py
  version/version.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XXL

#27 docs: Add design document
  README.md
  docs/design.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#30 *: Support PyTorch
  Gopkg.lock
  README.md
  docs/demo.md
  docs/examples/pytorch/example.ipynb
  docs/examples/tensorflow/example.ipynb
  pkg/backend/kubeflow/kubeflow.go
  pkg/backend/kubeflow/labels.go
  pkg/backend/kubeflow/pytorchjob.go
  pkg/backend/kubeflow/tfjob.go
  pkg/interpreter/simple/simple.go
  pkg/kernel/kernel.go
  pkg/manager/manager.go
  pkg/s2i/mock/mock.go
  pkg/s2i/simple/simple.go
  pkg/s2i/types.go
  s2i/pytorch-s2i/Dockerfile
  s2i/pytorch-s2i/s2i/bin/assemble
  s2i/pytorch-s2i/s2i/bin/run
  s2i/pytorch-s2i/s2i/bin/usage
  s2i/pytorch-s2i/test/test-app/code.py
  vendor/github.com/kubeflow/pytorch-operator/.gcloudignore
  vendor/github.com/kubeflow/pytorch-operator/.gitignore
  vendor/github.com/kubeflow/pytorch-operator/.travis.yml
  vendor/github.com/kubeflow/pytorch-operator/Dockerfile
  vendor/github.com/kubeflow/pytorch-operator/Gopkg.lock
  vendor/github.com/kubeflow/pytorch-operator/Gopkg.toml
  vendor/github.com/kubeflow/pytorch-operator/LICENSE
  vendor/github.com/kubeflow/pytorch-operator/OWNERS
  vendor/github.com/kubeflow/pytorch-operator/README.md
  vendor/github.com/kubeflow/pytorch-operator/build_image.sh
  vendor/github.com/kubeflow/pytorch-operator/linter_config.json
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/defaults.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/defaults_test.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/register.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/types.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha1/zz_generated.defaults.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/constants.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/defaults.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/register.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/types.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1alpha2/zz_generated.defaults.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/pytorchjob.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/generated_expansion.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/kubeflow_client.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/pytorchjob.go
  vendor/github.com/kubeflow/pytorch-operator/prow_config.yaml
  vendor/github.com/kubeflow/pytorch-operator/releasing.md
  vendor/github.com/kubeflow/pytorch-operator/submit_release_job.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#31 installation: Add s2i images
  docs/installation.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#36 Fix links
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#33 s2i: Add img support
  README.md
  cmd/kubeflow-kernel/command/run.go
  docs/installation.md
  pkg/config/config.go
  pkg/s2i/img/img.go
  pkg/s2i/img/template.go
  pkg/s2i/simple/simple.go
  s2i/pytorch-s2i/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#39 img: Add login
  cmd/kubeflow-kernel/command/run.go
  pkg/config/config.go
  pkg/s2i/img/img.go
  pkg/s2i/img/template.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#44 Fix a typo in README.md
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
